services:
  db:
    image: pgvector/pgvector:pg17
    container_name: rb-postgres
    environment:
      POSTGRES_USER: rbuser
      POSTGRES_PASSWORD: rescue
      POSTGRES_DB: rescuebox
    volumes:
      - ./init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "rbuser" ]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5433:5432"
