[pytest]
addopts = -p no:warnings --import-mode=prepend
asyncio_mode = auto
pythonpath =
    .
    src/rb-api
    src/rb-lib
    src/face-detection-recognition
    src/image-embeddings
    src/image-similarity
    src/image-summary
    src/text-summary
    src/text-embeddings
    src/audio-transcription
    src/age_and_gender_detection
    src/case-export
    src/ufdr-mounter
    src/deepfake-detection
    src/file-utils