[pytest]
addopts = -p no:warnings --import-mode=importlib
asyncio_mode = auto
pythonpath =
    .
    src/rb-api
    src/image-embeddings
    src/image-similarity
    src/image-summary
    src/face-detection-recognition