[tool.poetry]
name = "rb-api"
version = "3.0.0"
description = ""
authors = ["Jagath Jai Kumar <jagath.jaikumar@gmail.com>"]
packages = [{ include = "rb", from = "." }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "*"
uvicorn = "*"
jinja2 = "*"
makefun = "*"
typer = "*"

rescuebox = { path = "../../", develop = true }
rb-lib = { path = "../rb-lib", develop = true }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
