[project]
name = "video-summarizer"
version = "0.1.0"
description = ""
authors = [
    {name = "sachint2001",email = "sachin.t2001@gmail.com"}
]
readme = "README.md"
dependencies = [
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
