# This file is auto-generated by PipelineGenerator. Do not edit manually.

from celery import chain
from .rb_celery import run_audio_plugin, run_text_summarization_plugin


# Pipeline definition for: audio_to_summary
def run_audio_to_summary_pipeline(*args, **kwargs):
    """Return the celery chain signature for the audio_to_summary pipeline"""
    pipeline = chain(
        run_audio_plugin.s(),
        run_text_summarization_plugin.s(
            {
                "output_dir": "pipeline_output"
            },
            {
                "model_name": "gemma3:1b"
            }
        ),
    )
    return pipeline
