name: Pytest

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install --with api --with dev

      - name: Create required files
        run: |
          mkdir src/deepfake-detection/deepfake_detection/onnx_models
          touch src/deepfake-detection/deepfake_detection/onnx_models/bnext_M_dffd_model.onnx
          touch src/deepfake-detection/deepfake_detection/onnx_models/bnext_S_coco_model.onnx
          touch src/deepfake-detection/deepfake_detection/onnx_models/dima_transformer.onnx
          touch src/deepfake-detection/deepfake_detection/onnx_models/transformer_model_deepfake.onnx


      - name: Run tests
        run: poetry run pytest
