name: Pytest

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ffmpeg and libfuse-for-ufdr
        run: sudo apt-get update && sudo apt-get install -y ffmpeg && sudo apt install fuse

      - name: docker comose for pgvector
        run: ./startup/pgvector_start.sh
        
      - name: pull onnx model for deepfake
        run: |
          pip install gdown
          mkdir =p "src/deepfake-detection/deepfake_detection/onnx_models"
          
          

      - name: pull onnx model for facematch
        run: |
          pip install gdown --force-reinstall
          mkdir -p "src/face-detection-recognition/face_detection_recognition/models"
          
          
      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install --with api --with dev

      - name: Run tests
        env:
          DATABASE_URL: postgresql+psycopg2://rbuser:rescue@127.0.0.1:5433/rescuebox
        run: HF_HUB_OFFLINE=0 poetry run pytest --ignore=frontend/tests/integration/
