name: Pytest

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install --with api --with dev

      - name: Create required files
        run: |
          pip install gdown
          mkdir src/deepfake-detection/deepfake_detection/onnx_models
          gdown "1tFHTXCGy0hWRFH2H9MP9MpaBJvyHbW0u" --fuzzy -O src/deepfake-detection/deepfake_detection/onnx_models/bnext_M_dffd_model.onnx --continue
          gdown "1J1PjIFekJ0LEp3MxJ8ReOBmnqe5-4na6" --fuzzy -O src/deepfake-detection/deepfake_detection/onnx_models/bnext_S_coco_model.onnx --continue
          gdown "1z1R8E8xXvIhIgRGSK0HWg3-T0n750b6l" --fuzzy -O src/deepfake-detection/deepfake_detection/onnx_models/dima_transformer.onnx --continue
          gdown "1Ve2n-qq-zwfeBJLmeCV2XneHGb37Bgjq" --fuzzy -O src/deepfake-detection/deepfake_detection/onnx_models/transformer_model_deepfake.onnx --continue

      - name: Run tests
        run: poetry run pytest
